amcl:
  ros__parameters: {}
bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_mppi_controller::MPPIController"
      time_steps: 30
      model_dt: 0.05
      batch_size: 1500
      vx_max: 0.8
      vx_min: -0.2
      vy_max: 0.0
      wz_max: 1.6
planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
behavior_server:
  ros__parameters:
    use_sim_time: true
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      update_frequency: 10.0
      publish_frequency: 10.0
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      footprint: [[0.20, 0.15], [0.20, -0.15], [-0.20, -0.15], [-0.20, 0.15]]
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: /scan
          clearing: true
          marking: true
          max_obstacle_height: 2.0
          obstacle_range: 6.0
          raytrace_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 3.0
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 50
      height: 50
      resolution: 0.05
      track_unknown_space: true
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: lidar
        lidar:
          topic: /scan
          clearing: true
          marking: true
          max_obstacle_height: 2.0
          obstacle_range: 6.0
          raytrace_range: 8.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.65
        cost_scaling_factor: 3.0
map_server:
  ros__parameters: {}
lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ["controller_server","planner_server","bt_navigator"]
