<?xml version="1.0"?>
<robot name="linear_guide_system" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parameters -->
  <xacro:property name="column_height" value="0.5"/>
  <xacro:property name="column_width"  value="0.05"/>
  <xacro:property name="base_height"   value="0.05"/>
  <xacro:property name="base_width"    value="0.15"/>

  <!-- Materials -->
  <material name="gray">
    <color rgba="0.6 0.6 0.6 1.0"/>
  </material>
  <material name="dark_gray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <!-- World anchor link -->
  <link name="base_footprint"/>

  <!-- Column -->
  <link name="linear_guide_column">
    <visual>
      <origin xyz="0 0 ${column_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${column_width} ${column_width} ${column_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${column_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${column_width} ${column_width} ${column_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <origin xyz="0 0 ${column_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0"
               iyy="0.01" iyz="0"
               izz="0.01"/>
    </inertial>
  </link>

  <!-- Moving base -->
  <link name="linear_guide_base">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0" ixz="0"
               iyy="0.005" iyz="0"
               izz="0.005"/>
    </inertial>
  </link>

  <!-- Joints -->
  <joint name="linear_guide_column_fixed" type="fixed">
    <parent link="base_footprint"/>
    <child link="linear_guide_column"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <joint name="linear_guide_prismatic_joint" type="prismatic">
    <parent link="linear_guide_column"/>
    <child link="linear_guide_base"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="0.5" effort="50.0" velocity="0.2"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- ros2_control -->
  <ros2_control name="linear_guide_system" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="linear_guide_prismatic_joint">
      <command_interfaces>
        <command_interface name="position"/>
      </command_interfaces>
      <state_interfaces>
        <state_interface name="position"/>
        <state_interface name="velocity"/>
      </state_interfaces>
    </joint>
  </ros2_control>

</robot>
