controller_manager:
  ros__parameters:
    update_rate: 50

    column_position_controller:
      type: position_controllers/JointPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

column_position_controller:
  ros__parameters:
    joint: base_to_column_joint
