controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base:
      type: diff_drive_controller/DiffDriveController

    slider_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_drive_base:
  ros__parameters:
    left_wheel_names: ["bl_1"]
    right_wheel_names: ["br_1"]
    wheel_separation: 0.4
    wheel_radius: 0.1
    publish_rate: 50.0
    use_stamped_vel: false
    cmd_vel_timeout: 0.25
    enable_odom_tf: true

slider_position_controller:
  ros__parameters:
    joints: ["slider_joint"]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]

arm_controller:
  ros__parameters:
    joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "joint7"]
    command_interfaces: ["position"]
    state_interfaces: ["position", "velocity"]
